Repository LuanRT/YouTube.js, pull requests merged in 2022-07, with the labels that each got.

#92 refactor: rewrite search suggestions logic
  build/browser.js
  build/browser.js.map
  build/node.js
  build/node.js.map
  lib/Innertube.js
  lib/core/Actions.js
  lib/core/Music.js
  lib/parser/contents/classes/HistorySuggestion.js
  lib/parser/contents/classes/MusicShelf.js
  lib/parser/contents/classes/SearchSuggestion.js
  lib/parser/contents/classes/SearchSuggestionsSection.js
  lib/parser/contents/classes/TabbedSearchResults.js
  lib/parser/contents/map.js
  lib/parser/youtube/VideoInfo.js
  lib/parser/ytmusic/HomeFeed.js
  test/browser/main.test.js
  test/node/main.test.js
  typings/lib/Innertube.d.ts
  typings/lib/core/Actions.d.ts
  typings/lib/core/Music.d.ts
  typings/lib/parser/contents/classes/HistorySuggestion.d.ts
  typings/lib/parser/contents/classes/SearchSuggestion.d.ts
  typings/lib/parser/contents/classes/SearchSuggestionsSection.d.ts
  typings/lib/parser/contents/classes/TabbedSearchResults.d.ts
  typings/lib/parser/contents/index.d.ts
  typings/lib/parser/ytmusic/HomeFeed.d.ts
Labels: enhancement, priority: medium

#114 refactor: generate typescript protobuf encoders
  browser.ts
  package-lock.json
  package.json
  src/core/Actions.ts
  src/proto/index.js
  src/proto/index.ts
  src/proto/messages.js
  src/proto/youtube.proto
  src/proto/youtube.ts
  src/utils/Utils.ts
Labels: enhancement, dependencies

#115 feat: add support for uploading videos
  package-lock.json
  src/core/Session.ts
  src/core/Studio.ts
  src/utils/Constants.ts
  src/utils/HTTPClient.ts
Labels: enhancement
