Repository LuanRT/YouTube.js, pull requests merged in 2024-03, with the labels that each got.

#620 fix(Cache): handle the value read from the db correctly according to its type
  src/platform/web.ts
Labels: small-diff

#617 chore(LockupView): Remove debug logging
  src/parser/classes/LockupView.ts
Labels: parser, xsmall-diff

#618 Fix broken README links
  examples/comments/README.md
  examples/livechat/README.md
Labels: docs, xsmall-diff

#624 fix(PlayerEndpoint): Workaround for "The following content is not available on this app" (Android)
  src/core/Session.ts
  src/core/endpoints/PlayerEndpoint.ts
  src/proto/generated/messages/youtube/(ShortsParam)/Field1.ts
  src/proto/generated/messages/youtube/(ShortsParam)/index.ts
  src/proto/generated/messages/youtube/ShortsParam.ts
  src/proto/generated/messages/youtube/index.ts
  src/proto/index.ts
  src/proto/youtube.proto
  src/utils/Constants.ts
  src/utils/HTTPClient.ts
  test/main.test.ts
Labels: core, protobuf, medium-diff, tests

#596 feat: add support of cloudflare workers runtime
  examples/cloudflare-worker/package.json
  examples/cloudflare-worker/src/index.ts
  examples/cloudflare-worker/tsconfig.json
  examples/cloudflare-worker/wrangler.toml
  package.json
  src/platform/cf-worker.ts
  src/types/PlatformShim.ts
  src/utils/HTTPClient.ts
Labels: medium-diff
